adicionando crud do projeto
pablitz/poc-cloud pull request #2
Opened 2021-09-16 20:54 UTC by pablitz

2021-09-17 11:57 UTC, edersonrsilva requested changes
Pablo, fiz vários comentários solicitando modificações no projeto.
O projeto tem alguns erros mas no geral ele está funcional, mas vou ensinar para você uma forma mais enxuta e próxima do que você vai encontrar no seu dia a dia.
Tente fazer as correções que eu solicitei e se você tiver alguma dúvida pode me pingar.
Não precisa correr, pode fazer com calma, ir pesquisando suas dúvidas. 
Lembre-se que não estou avaliando nada, estou aqui para ajudar e compartilhar conhecimento.

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/controller/PersonController.java
> +@RequestMapping("/Persons")
Utilize sempre nomes com letras minúsculas. Se houver mais de uma palavra use hífen para separá-las, ex: persons-details

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/controller/PersonController.java
> +    PersonService personService;
Essa forma está correta e é funcional, mas existe uma prática mais recomendada e utilizado no mercado.
Faça a injeção pelo construtor, o Lombok pode ajudar nessa abordagem. Fazendo isso a annotation @Autowired não será mais necessária. Dê uma pesquisa e se tiver dúvidas me avise.

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/controller/PersonController.java
> +    public Page<PersonDTO> list(@RequestParam(required = false) String namePerson,
Vou escrever aqui uma geral do métodos, eu preciso que tenhamos nessa classe esses 5 métodos:
- listar tudo - sem parâmetros e retorna List<Person>
- retornar um - recebe um ID e retorna Person
- adicionar - recebe dados de person e retorna o person inserido no banco
- alterar - recebe dados de person e retorna o person alterado no banco
- excluir - recebe um ID e não retorna nada (claro que o ID informado deve ser excluido no banco)
Nos métodos só utilize as annotations @GetMapping, post, put e delete, nenhuma outra é necessária.

Tente fazer dessa forma e qualquer coisa me consulte

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/dto/PagePersonDTO.java
> +package br.com.pga.restkafka.dto;
Não precisamos de classe, pode removê-la

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/dto/PersonDTO.java
> +package br.com.pga.restkafka.dto;
Não precisamos de classe, pode removê-la.

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/dto/PersonResponseDTO.java
> +package br.com.pga.restkafka.dto;
Não precisamos dessa classe, pode removê-la.

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +import lombok.*;
Tente configurar a sua IDE conforme a figura abaixo, para que ela não coloque * nos imports.

![image](https://user-images.githubusercontent.com/10835443/133776598-09ba525f-0bbd-4b9e-86ee-0999b772581e.png)

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +@EqualsAndHashCode
Essa annotation é desnecessária, o @Data já cria o Equals e Hash.

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +    @Column(name="FIRSTNAME")
Como o nome da coluna no banco e do atributo da app são os mesmos, a propriedade name não se faz necessária, pode colocar, mas não faz diferença.

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +    private int age;
Em entidades de banco, se você usa um tipo primitivo com int, long, double, pode ocorrer um problema. No seu caso, se você não informar a idade na hora da inclusão ou alteração, o Java vai atribuir o valor 0, já que tipos primitivos não aceitam NULL. Então se você não tem certeza quanto e esse fato, trabalhe sempre com objetos: Integer, Long, Double.
Se quiser trocar uma idéia sobre isso me fala.

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/repository/PersonRepository.java
> +    Page<Person> findByFirstName(String name, Pageable pageable);
Esse método é desnecessário. Somente a interface extendendo JpaRepository irá nos atender nesse momento.

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonService.java
> +    private PersonRepository personRepository;
Tente injetar essa dependencia pelo construtor, com ou sem ajuda do Lombok.

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonService.java
> +    public static Page<PersonDTO> convert(Page<Person> Persons) {
Método desnecessário

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonService.java
> +    public Person convertResponse(PersonResponseDTO personResponseDTO) {
Método desnecessário

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonService.java
> +    public Person convertResponseUpdate(long id, PersonResponseDTO personResponseDTO) {
Método desnecessário

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonService.java
> +    public Page<PersonDTO> listPersons(String namePerson, Pageable paginacao) {
Vou dar uma geral para o resto da classe.
Queremos os seguintes métodos:
- listar tudo - retorna List<Person>
- retornar um - retorna Person
- adicionar - retorna Person
- alterar - retorna Person
- excluir - retorna Void

2021-09-17 11:57 UTC, edersonrsilva commented on restkafka/src/main/resources/data.sql
> +INSERT INTO Person(firstName, surName, age, email) VALUES('josé','da silva','25' ,'josedasilva@gmail.com');
Vamos trabalhar sem acentuação nesse momento, vamos achar que somos gringos e não temos acentos em nosso idioma.
Nesse momento os acentos trazem uma dificuldade que não precisamos.

E não estão faltando as datas nesses inserts?

2021-09-17 19:03 UTC, pablitz commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +    private int age;
quero sim , se possivel.

2021-09-17 19:16 UTC, pablitz commented on restkafka/src/main/java/br/com/pga/restkafka/dto/PersonResponseDTO.java
> +package br.com.pga.restkafka.dto;
eu usei só 1 DTO mas deixei justamente essa.

2021-09-17 19:17 UTC, pablitz commented on restkafka/src/main/java/br/com/pga/restkafka/dto/PersonResponseDTO.java
> +package br.com.pga.restkafka.dto;
não preciso usar nenhum ?

2021-09-17 19:17 UTC, pablitz commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +    @Column(name="FIRSTNAME")
ok

2021-09-17 19:40 UTC, edersonrsilva requested changes
Fiz umas pequenas correções.
Acredito que está quase finalizado, faltando alguns detalhes.
Faça as correções e me avise.

**OBS:** Quando vc atender as minhas considerações, clique no botão Resolve conversation. Se você quiser também pode responder e colocar seu ponto de vista.

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/controller/PersonController.java
> +    PersonServices personService;
Acho que o nome PersonService fica melhor.
E esse tipo de variável deve ser anotada com private final

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/controller/PersonController.java
> +
Anotação deve ficar colada no método

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/controller/PersonController.java
> +    public Person update(@PathVariable Long id, @RequestBody PersonResponseDTO personResponseDTO) {
Vamos trabalhar só com @RequestBody, vamos usar Person mesmo, sem necessidade de DTO.
Depois vamos inserir no projeto classes de Request e Response.
Por enquanto mantemos com Person.

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/dto/PersonResponseDTO.java
> +package br.com.pga.restkafka.dto;
Pode remover essa classe

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +package br.com.pga.restkafka.model;
espaço entre package e import

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +import java.time.LocalDateTime;
espaço em o import e as anotações

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
Acho que não precisamos dessa anotação

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +    @Column(name="FIRSTNAME")
Fez um teste sem informar o atributo name da anotação Column?

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/repository/PersonRepository.java
> +
remova essas linhas em branco

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonServices.java
> +    PersonRepository personRepository;
private final

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonServices.java
> +public class PersonServices {
PersonService?

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonServices.java
> +    public List<Person> listPersons() {
Que tal o nome findAll?

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonServices.java
> +    public Person returnOne(long id) {
Que tal o nome findById?

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonServices.java
> +    public Person addOne(Person person) {
Que tal add ou create?

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonServices.java
> +    public Person update(Long id, PersonResponseDTO personResponseDTO) {
Vamos receber apenas o Person.
Depois criaremos um Person Request

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonServices.java
> +        person.setEmail(personResponseDTO.getEmail());
Isso não é necessário por agora. Trabalhe com Person apenas.

2021-09-17 19:40 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/services/PersonServices.java
> +    public void remove(Long id) {
Boa, esse método está muito bom.
Depois vamos deixar otimizar ele.

2021-09-17 20:06 UTC, pablitz commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
deu erro quando quando usava um put ou post

2021-09-17 20:18 UTC, pablitz commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +    @Column(name="FIRSTNAME")
não,  vou fazer mas já sabia que era opcional, acho que fica mais organizado assim.

2021-09-17 20:54 UTC, pablitz commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +    @Column(name="FIRSTNAME")
testei sem e não funcinou.

2021-09-20 13:41 UTC, edersonrsilva approved these changes

2021-09-20 13:41 UTC, edersonrsilva commented on restkafka/src/main/java/br/com/pga/restkafka/model/Person.java
> +@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
Cara, nunca usei essa propriedade e sempre funcionou.

2021-09-20 13:50 UTC, merged